### ISSUE TITLE
Dependabot breaks CI at "Ensure generated files are up-to-date"

### ISSUE THREAD

**Issue by andreasabel** [haskell-actions/setup#33]
@brandonchinn178 You introduced a new check to CI in https://github.com/haskell-actions/setup/pull/21/commits/906b3bf78367868c0922be04809e68a7ef7eb477 testing whether the generated JS is in sync with the TS.

This check seems to break when dependabot updates a dependency, see e.g. the bump of `compare-versions`:
-https://github.com/haskell-actions/setup/pull/28
- https://github.com/haskell-actions/setup/actions/runs/6044741804/job/16403764725?pr=28

Either CI or dependabot is off here.  Not sure we can change dependabot, but I don't know.
Could you have a look?

**Comment by brandonchinn178** [comment]
Sure; if the dependency is bundled in the generated files, then changing the dependency requires changing the files. If you still want dependabot PRs, youll need to check out the branch, regen the files, and push. If you have multiple dependabot PRs, perhaps you can merge as admin (override the check) and regen on master all at once.

This is a good thing; it means that the generated code is in sync with the project. And it means that someone checking out the repo fresh doesnt have out of sync files. For example, if someone makes a README-only change while generated files are out of sync from a dependabot bump, then their PR would be broken due to something unrelated.

If you dont want dependabot PRs at all, you can disable them in the settings. Or perhaps a better alternative is to not commit the generated files and just generate them at release, on a separate branch

**Comment by mihaimaruseac** [comment]
Could be fixed by running something similar to

```console
...$ git fetch upstream dependabot/go_modules/github.com/99designs/gqlgen-0.17.33
...$ git switch dependabot/go_modules/github.com/99designs/gqlgen-0.17.33
...$ make generate
...$ git add ....
...$ git commit ....
...$ git push ....
```

(tested on another repo, https://github.com/guacsec/guac/pull/953#issuecomment-1599090212)

Alternatively, the CI could be made to update the files on a specific comment (as the files should be updated automatically only when actually desired)

**Comment by andreasabel** [comment]
@mihaimaruseac wrote:
> ```
> ...$ # regenerate the files
> ```

What is the magic incanation to regenerate them?

I thought keeping the files up to date was the job of the husky scripts invoked with `git commit` and `git push`.  However, they do not seem to do this: https://github.com/haskell-actions/setup/actions/runs/6130024354/job/16638735185

**Comment by brandonchinn178** [comment]
So in this commit https://github.com/haskell-actions/setup/commit/0cab6f57ca63e907d25895e0242c529282f1cdc8, notice that dist/index.js changed a lot more than just the version that you changed. That should be an indication that your environment probably isnt up to date and is generating with out of date files.

Specifically, the extra changes made in that commit reverts the changes made here: https://github.com/haskell-actions/setup/commit/3622c430bca14224ad73e009ac126ac1c890a432

That commit explains that this is due to having the wrong version of @actions/io installed. Did you run npm install before regenerating the files? The changes that were generated in your commit come from a different version of @actions/io than the version specified in package-lock.json

**Comment by mihaimaruseac** [comment]
Can the regenerate be made to run as a self-contained script that covers all cases? I'm not yet up to date with all the code in the repo, so I'm unsure
